# This is a basic workflow to help you get started with Actions

name: CI
env: 
  EMAIL_KEY: ${{ secrets.EMAIL_KEY}}
  EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS}}

on:
  schedule:
    - cron: 0 */5 * * *
  workflow_dispatch:

jobs:
  scrape-latest:
    name: scrape-latest
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python -m pip install selenium requests pandas beautifulsoup4 tabula-py geopy unidecode webdriver-manager email-to
          
      - id: install-chromedriver
        name: Install chromedriver
        uses: nanasess/setup-chromedriver@master

      - name: Scrape
        shell: bash
        run: |
          python scraper.py

      - name: Email
        shell: bash
        run: |
          python notif.py
        
      - name: Add and commit and push
        run: |
          git fetch
          git pull
          git add --all
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git commit -m "Latest data" 
          git push